server:
  port: ${SERVER_PORT:8092}
  servlet:
    context-path: /jspmzlh3z
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 600MB
      max-request-size: 600MB
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp


#  datasource: #定义数据源
#    url: jdbc:mysql://127.0.0.1:3306/jspmzlh3z?serverTimezone=GMT%2B8&useSSL=FALSE
#    username: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
  datasource:
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    type: ${spring.datasource.type}

