server:
  port: ${SERVER_PORT:8092}
  servlet:
    context-path: /jspmzlh3z
    encoding:
      charset: utf-8
      enabled: true
    register-default-servlet: true
spring:
  servlet:
    multipart:
      max-file-size: 31MB
      max-request-size: 31MB


  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
    static-path-pattern: /**


  datasource: #定义数据源
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/jspmzlh3z?serverTimezone=GMT%2B8&useSSL=FALSE}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:admin}
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 0
      max-active: 20
      max-idle: 20
      min-idle: 0
      max-wait: 60000
      validation-query: SELECT 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 25200000
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true
      filters: mergeStat




